name: sqflite_migrations
description: Migrations manager for sqflite.
version: 0.1.0
homepage: https://github.com/LeandroDoldan/sqflite_migrations
author: Leandro Doldan <leandromdoldan@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqflite: ^1.1.6